name: Docker Build

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Gitea Registry
        run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login ${{ gitea.server_url }} -u ${{ gitea.actor }} --password-stdin

      - name: Build image
        run: |
          docker build \
            -t ${{ gitea.server_url }}/${{ gitea.repository }}:latest \
            -f docker/Dockerfile .

      - name: Push image
        run: |
          docker push ${{ gitea.server_url }}/${{ gitea.repository }}:latest