version: "3.9"

services:
  downloader:
    image: tubarr:latest

    container_name: tubarr

    ports:
      - "5000:5000"

    volumes:
      - ./downloads:/app/downloads
      - ./youtube:/app/youtube
      - ./data:/app/data

    environment:
      - PYTHONUNBUFFERED=1
      - OS_ENV_FILE=windows
      - DOWNLOADS_DIR=downloads
      - YOUTUBE_DIR=youtube
      - DEBUG=False

    restart: unless-stopped